### ISSUE TITLE
Feature request: default settings

### ISSUE THREAD

**Issue by ajansveld** [FrodgE/fetch-user-environment#1]
Great extension! Would it be possible to add a file with default settings, that only get imported if the user has not specified them already?

**Comment by FrodgE** [comment]
Hi @ajansveld,
I'm glad to hear you have found the extension helpful!  That's a great idea, thank you for your suggestion.  Keep an eye out for an update to the extension soon 😄
Regards,
Michael.

**Comment by FrodgE** [comment]
Hi @ajansveld,
"Fetch User Environment" version 1.1.0 has now been released to the marketplace.  I hope this meets your needs.  Please let me know if you have any issues or have further suggestions.
If you have found this extension helpful would you kindly consider leaving a review on the marketplace? :smiley: :thumbsup:
Regards,
Michael.
