### ISSUE TITLE
Load default settings with "Fetch settings"

### ISSUE THREAD

**Issue by ajansveld** [FrodgE/fetch-user-environment#2]
Thanks for the default settings feature update (#1) ! Those settings apply when vscode is reloaded, can you make them also apply when the "Fetch settings" command is run from the command palette?

**Comment by FrodgE** [comment]
Hi @ajansveld,
Thank you for your kind review on the marketplace, I appreciate it 😄

The same comparison functions are executed regardless of how they are invoked.  So calling "Fetch settings" from the command palette does also check the default settings.  At a guess I suspect the following might be happening...
You would have configured & created a default settings file.  Upon VS Code starting it would compare the default settings file against the current user configuration file and any settings that have not been specified within the user configuration file would have been added.  All settings within the default settings file will now exist in some manner in the user settings file, and are therefore now a _user defined_ setting.  Calling "Fetch settings" again either upon VS Code start or from the command palette will now skip over these existing _"user defined"_ settings.  You could test this idea by adding new settings to the default settings file or by deleting some settings from your user settings (no need to restart), and then invoke the command from the palette.

It can become a grey line between default settings and mandatory settings.  I'm wondering if it would be useful to add a 3rd settings file that specifies settings to delete?  Doing this however would have a nearly identical effect as a mandatory setting so perhaps the added complexity and resulting confusion would not be worth it?

Anyway let me know how you go.  I've tested the functionality of the default settings file from both restarting VS Code and the command palette and didn't notice any issues, but it's possible I've missed something.

Regards,
Michael.

**Comment by ajansveld** [comment]
You are correct, I tested again with the latest vscode version and could not reproduce the issue.

Thanks!
