### ISSUE TITLE
Ignore workspace settings

### ISSUE THREAD

**Issue by ajansveld** [FrodgE/fetch-user-environment#3]
If a workspace setting overrides a user setting that is managed by the extension, the extension will keep prompting to restart/reload the vscode session (since this is actually not "fixable"). 

Seems like the extension should ignore workspace settings altogether.

Thanks!

**Comment by FrodgE** [comment]
Hi @ajansveld, thanks for the bug report.  I've been pretty busy recently so I haven't had a chance to look in to it yet.  Hopefully soon...

**Comment by FrodgE** [comment]
Hi @ajansveld, sorry for the delay and thank you for your patience.  I've just published version 1.1.1 which should fix the problem.
I had been comparing the remote settings to the active workspace deliberately to try and avoid unnecessary clutter in the user settings file if a setting defined in the remote was the same as the default.  I considered having the extension check and update the workspace settings but decided that might be too dangerous.  Instead the extension now just simply compares the user settings file to the remote settings file.
Let me know if you have any trouble.
Regards,
Michael.

**Comment by ajansveld** [comment]
Works great!
