### ISSUE TITLE
Extensions are always reinstalled 

### ISSUE THREAD

**Issue by BrunoMacias** [FrodgE/fetch-user-environment#6]
Starting with the Visual Studio Code update 1.24 every time I launch VSCode it tells me my extensions have been updated.

**Comment by BrunoMacias** [comment]
This should be resolved once https://github.com/Microsoft/vscode/issues/51387 is relased

**Comment by davidmarkscott** [comment]
The [VSCode issue (Microsoft/vscode#51387)](https://github.com/Microsoft/vscode/issues/51387) has been added to the VSCode May Recovery milestone and marked as Closed.
